name: zeno
description: A hot reload utility for Dart Applications
version: 0.0.1


environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.0
  path: ^1.9.1
  pub_updater: ^0.4.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  zeno:
